name: Test and deploy demo
on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node & NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Build demo
        if: github.ref == 'refs/heads/master'
        run: npm run build:demo

      - name: Deploy demo
        if: github.ref_name == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist
          destination_dir: ${{ github.ref_name }}
          keep_files: true
